extends Node

const PLAYER_MAX_HEALTH := 100.0
const PLAYER_MAX_STAMINA := 100.0
const PLAYER_MOVE_SPEED := 355.0
const PLAYER_ACCELERATION := 2600.0
const PLAYER_DECELERATION := 3000.0
const PLAYER_ATTACK_COST := 18.0
const PLAYER_DODGE_COST := 34.0
const PLAYER_ATTACK_DAMAGE := 28.0
const PLAYER_ATTACK_KNOCKBACK := 280.0
const PLAYER_ATTACK_WINDUP_TIME := 0.09
const PLAYER_ATTACK_ACTIVE_TIME := 0.10
const PLAYER_ATTACK_RECOVERY_TIME := 0.16
const PLAYER_ATTACK_BUFFER_WINDOW := 0.11
const PLAYER_DODGE_SPEED := 760.0
const PLAYER_DODGE_TIME := 0.27
const PLAYER_DODGE_INVULN_TIME := 0.18
const PLAYER_DODGE_RECOVERY := 0.09
const PLAYER_HEAL_AMOUNT := 38.0
const PLAYER_HEAL_TIME := 0.75
const PLAYER_STAMINA_REGEN := 62.0
const PLAYER_STAMINA_REGEN_DELAY := 0.30
const PLAYER_HURT_TIME := 0.22

const ENEMY_MAX_HEALTH := 86.0
const ENEMY_MOVE_SPEED := 165.0
const ENEMY_DETECT_RANGE := 620.0
const ENEMY_ATTACK_RANGE := 104.0
const ENEMY_ATTACK_DAMAGE := 18.0
const ENEMY_ATTACK_KNOCKBACK := 260.0
const ENEMY_WINDUP_TIME := 0.52
const ENEMY_ACTIVE_TIME := 0.16
const ENEMY_RECOVERY_TIME := 0.68
const ENEMY_STAGGER_HITS := 3
const ENEMY_STAGGER_TIME := 0.42
const ENEMY_PATROL_RADIUS := 80.0

const ARENA_HALF_SIZE := Vector2(760.0, 390.0)
