extends Node

const PLAYER_MAX_HEALTH := 100.0
const PLAYER_MAX_STAMINA := 100.0
const PLAYER_MOVE_SPEED := 325.0
const PLAYER_ACCELERATION := 1900.0
const PLAYER_DECELERATION := 2300.0
const PLAYER_ATTACK_COST := 18.0
const PLAYER_DODGE_COST := 34.0
const PLAYER_ATTACK_DAMAGE := 28.0
const PLAYER_ATTACK_KNOCKBACK := 280.0
const PLAYER_ATTACK_WINDUP_TIME := 0.11
const PLAYER_ATTACK_ACTIVE_TIME := 0.17
const PLAYER_ATTACK_RECOVERY_TIME := 0.20
const PLAYER_DODGE_SPEED := 690.0
const PLAYER_DODGE_TIME := 0.25
const PLAYER_DODGE_RECOVERY := 0.10
const PLAYER_HEAL_AMOUNT := 38.0
const PLAYER_HEAL_TIME := 0.75
const PLAYER_STAMINA_REGEN := 52.0
const PLAYER_STAMINA_REGEN_DELAY := 0.42
const PLAYER_HURT_TIME := 0.22

const ENEMY_MAX_HEALTH := 86.0
const ENEMY_MOVE_SPEED := 150.0
const ENEMY_DETECT_RANGE := 620.0
const ENEMY_ATTACK_RANGE := 104.0
const ENEMY_ATTACK_DAMAGE := 18.0
const ENEMY_ATTACK_KNOCKBACK := 260.0
const ENEMY_WINDUP_TIME := 0.58
const ENEMY_ACTIVE_TIME := 0.18
const ENEMY_RECOVERY_TIME := 0.62
const ENEMY_STAGGER_HITS := 3
const ENEMY_STAGGER_TIME := 0.42
const ENEMY_PATROL_RADIUS := 80.0

const ARENA_HALF_SIZE := Vector2(760.0, 390.0)
